---
name: Build & Deploy on GitHub Actions

on:
    workflow_dispatch:
    schedule:
      - cron: "0 1 * * *"
    push:
        branches:
            - main

env:
  REGISTRY: docker.io

jobs:
    build:
        runs-on: ubuntu-24.04
        strategy:
            matrix:
                go-arch: [ 'amd64', 'arm64' ]
                go-os: [ 'linux', 'darwin', 'windows' ]

        steps:
        - name: Get Code from repo
          uses: actions/checkout@v4

        - name: Setup Go
          uses: actions/setup-go@v5
          with:
            go-version: '1.23'

        - run: |
            go mod init Projet/main.go
            go mod tidy
            GOOS=${{ matrix.go-os }} GOARCH=${{ matrix.go-arch }} go build -o "main_${{ matrix.go-os }}_${{ matrix.go-arch}}" Projet/main.go
        
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }} 

        # - name: Set up Docker Buildx # Cette step nous sert à Set Docker Buildx pour charger nos images pour les différent processeurs plus tard dans le job
        #   run: |
        #     docker buildx create --use

        - name: Docker meta
          id: meta
          uses: docker/metadata-action@v5
          with:
            images: |
                ${{ env.REGISTRY }}/${{ vars.DOCKERHUB_USERNAME }}/goCow

        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            context: .
            push: true
            tags: ${{ steps.meta.outputs.tags }}_${{ matrix.go-os }}_${{ matrix.go-arch}}
            labels: ${{ steps.meta.outputs.labels }}
            platforms: ${{ matrix.go-os}}/${{ matrix.go-arch }}


    #     - name: Upload Artifact
    #       uses: actions/upload-artifact@v4
    #       with:
    #         path: .
    #         name: goCow


    # deploy:
    #     runs-on: self-hosted
    #     needs: build
    #     steps: 
    #         - uses: actions/download-artifact@v4
    #           with:
    #             path: /var/www/go/
    #             name: goCow
