---
name: build and deliver cowsay app

on:
  workflow_dispatch:
    inputs:
      message: 
        description: 'a message to cowsay'
        required: true
        default: 'Go Cow Yourself!'

jobs:
  cowsay:
    name: a cow that says something
    runs-on: ubuntu-latest
    steps:
      - run: |
          whoami
          apt update
          apt -y install cowsay
          # le -y permet de répondre à la question yes/no de l'install
          # les actions ne gèrent pas cette fonctionnalité
          cowsay $MESSAGE
        env:
          MESSAGE: ${{ inputs.message }}

