---
name: build and deliver cowsay app

on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    build:
        name: build go code into binary
        runs-on: ubuntu-latest

        steps:
            - name: Get Code from repo
              uses: actions/checkout@v4

            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                go-version: '>=1.23'

            - run: |
                go mod init Projet/main.go
                go mod tidy
                go run Projet/main.go
                go build -o bin/goCow.go Projet/main.go

            - name: Upload static files as artifact
              id: deployment
              uses: actions/upload-artifact@v4 # or specific "vX.X.X" version tag for this action
              with:
                path: bin/
                name: cowsaybin
