---
name: build and deliver cowsay app

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version de l'image docker"
        required: false
        default: 'auto'
  push:
    branches:
        - main

env:
  REGISTRY: docker.io
  VERSION: ${{ vars.VERSION_TAG }} + 1

jobs:
  build:
    name: build go code into binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
          go-arch: [ 'amd64', 'arm64' ]

    steps:
      - name: Get Code from repo
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.23'

      - run: |
          go mod init Projet/main.go
          go mod tidy
          GOARCH=${{ matrix.go-arch }} go build -o bin/gocow Projet/main.go

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-artifact@v4 # or specific "vX.X.X" version tag for this action
        with:
          path: .
          name: cowsaybin-${{ matrix.go-arch }}
  
  push-docker:
    name: push in docker registry
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
          go-arch: [ 'amd64', 'arm64' ]
    steps:

      - uses: actions/download-artifact@v4
        with:
          path: .
          name: cowsaybin-${{ matrix.go-arch }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ vars.DOCKERHUB_USERNAME }}/gocow

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: "gocow:'v${{ env.VERSION }}'"
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/${{ matrix.go-arch }}

  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/download-artifact@v4
  #       with:
  #         path: .
  #         name: cowsaybin
  #     - run: ./Projet/main


