---
name: build and deliver cowsay app

on:
    workflow_dispatch:
        inputs:
            version:
                description: "Version de l'image docker"
                required: false
                default: 'auto'
    push:
        branches:
            - main

env:
    VERSION: ${{ github.event.inputs.version}}

jobs:
    build:
        name: build go code into binary
        runs-on: ubuntu-latest

        steps:
            - name: Get Code from repo
              uses: actions/checkout@v4

            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                go-version: '>=1.23'

            - name: récuperer le numero de verion
              id: version
              run: |
                # Si l'entrée version est laissée à "auto", on incrémente la version
                if [ "${{ github.event.inputs.version }}" == "auto" ]; then
                    # Vérifie si le fichier version.txt existe
                    if [ -f version.txt ]; then
                    # Lire la version actuelle et incrémenter
                        version=$(cat version.txt)
                        version_number=$(($version + 1))
                    else
                        # Si le fichier n'existe pas, on commence à la version 1
                        version_number=1
                    fi
                    # Sauvegarder la nouvelle version dans version.txt
                    echo "Nouvelle version: $version_number" > version.txt
                    echo "version=$version_number" >> $GITHUB_ENV
                else
                    # Si une version spécifique est fournie par l'utilisateur
                    echo "version=${{ github.event.inputs.version }}" >> $GITHUB_ENV
                fi

            - run: |
                go mod init Projet/main.go
                go mod tidy
                go run Projet/main.go
                go build -o bin/goCow.go Projet/main.go

            - name: Upload static files as artifact
              id: deployment
              uses: actions/upload-artifact@v4 # or specific "vX.X.X" version tag for this action
              with:
                path: bin/
                name: cowsaybin
    
    push-docker:
        name: push in docker registry
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build Docker Image
              run: |
                docker build -t gocow:${{ env.VERSION }} .

            - name: Push Docker Image
              run: |
                docker push ${{ vars.DOCKERHUB_USERNAME }}/gocow:${{ env.VERSION }}
            